"""Initial

Revision ID: 01137a0a2fd2
Revises: 
Create Date: 2022-06-20 20:08:36.096308

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01137a0a2fd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_units',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('parentId', postgresql.UUID(), nullable=True),
                    sa.Column('type', sa.Enum('category', 'offer', name='type'), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['parentId'], ['shop_units.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_units')
    # ### end Alembic commands ###
