"""Initial

Revision ID: d802c6c39700
Revises: 
Create Date: 2022-06-26 12:04:35.393328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd802c6c39700'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_units',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('category', 'offer', name='type'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('parentId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('children_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['shop_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_units_statistics',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('category', 'offer', name='type'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('parentId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['shop_units.id'], ),
    sa.PrimaryKeyConstraint('id', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_units_statistics')
    op.drop_table('shop_units')
    # ### end Alembic commands ###
