"""Initial

Revision ID: f43643c8263f
Revises: 
Create Date: 2022-06-22 16:37:24.111523

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f43643c8263f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_units',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('type', sa.Enum('category', 'offer', name='type'), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False, default=0),
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('parentId', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('children_item_count', sa.Integer(), nullable=False, default=0),
                    sa.CheckConstraint('children_item_count >= 0', name='check_children_item_count_non_negative'),
                    sa.ForeignKeyConstraint(['parentId'], ['shop_units.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('shop_units_statistics',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('type', sa.Enum('category', 'offer', name='type'), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('parentId', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['shop_units.id'], ),
                    sa.PrimaryKeyConstraint('id', 'date')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_units_statistics')
    op.drop_table('shop_units')
    # ### end Alembic commands ###
